export const environment = {
  production: true,
  urlRaiz: 'https://isaempresas.sharepoint.com',
  urlWeb:'https://isaempresas.sharepoint.com/sites/INTERNEXA/Solpes_test', 
  urlReltativa: '/sites/INTERNEXA/Solpes_test',
  listaEmpresas: 'Empresas',
  listaPaises: 'Paises',
  listaCategorias: 'Categorias',
  listaSubcategorias: 'Subcategorias',
  listaCondicionesContractuales: 'CondicionesContractuales',
  listaTiposSolicitud: 'TiposSolicitud',
  listaSolicitudes: 'Solicitudes',
  listaCondicionesTecnicasBienes: 'CondicionesTecnicasBienes',
  listaCondicionesTecnicasServicios: 'CondicionesTecnicasServicios',
  listaConfiguracion: 'ConfiguracionAplicacion',
  listaRecepcionBienes: 'RecepcionBienes',
  listaRecepcionServicios: 'RecepcionServicios',
  listaContratos: 'Contratos',
  listaResponsableProceso: 'ResponsableProceso',
  listaNotificaciones: 'Notificaciones',
  linkVistaEdicionContratos: '/Lists/Contratos/EdicionContratos.aspx',
  listaMotivoSuspension: 'motivoSuspension',
  listaCausalExcepcion: 'CausalExcepcion',
  listaCompradores: 'Compradores',
  listaHistorial: 'HistorialSuspensiones',
  listaSolicitudesCrm: 'SolicitudesCrm',
  listaResponsableSoporte: 'ResponsableSoporte',
  listaTipoEjecucion: 'TipoEjecucion',
  listaCausalIncumplimento: 'CausalIncumplimiento'
};