export const environment = {
  production: false,
  urlRaiz: 'https://isaempresas.sharepoint.com',
  urlWeb:'https://isaempresas.sharepoint.com/sites/INTERNEXA/Solpes', 
  urlReltativa: '/sites/jam/solpes',
  urlToken: 'https://login.microsoftonline.com/c980e410-0b5c-48bc-bd1a-8b91cabc84bc/oauth2/token',
  listaEmpresas: 'Empresas',
  listaPaises: 'Paises',
  listaCategorias: 'Categorias',
  listaSubcategorias: 'Subcategorias',
  listaCondicionesContractuales: 'CondicionesContractuales',
  listaTiposSolicitud: 'TiposSolicitud',
  listaSolicitudes: 'Solicitudes',
  listaCondicionesTecnicasBienes: 'CondicionesTecnicasBienes',
  listaCondicionesTecnicasServicios: 'CondicionesTecnicasServicios',
  listaConfiguracion: 'ConfiguracionAplicacion',
  listaRecepcionBienes: 'RecepcionBienes',
  listaRecepcionServicios: 'RecepcionServicios',
  listaContratos: 'Contratos',
  listaResponsableProceso: 'ResponsableProceso',
  listaNotificaciones: 'Notificaciones',
  linkVistaEdicionContratos: '/Lists/Contratos/EdicionContratos.aspx',
  listaMotivoSuspension: 'motivoSuspension',
  listaCausalExcepcion: 'CausalExcepcion',
  listaCompradores: 'Compradores',
  listaHistorial: 'HistorialSuspensiones',
  listaSolicitudesCrm: 'SolicitudesCrm',
  listaResponsableSoporte: 'ResponsableSoporte',
  listaTipoEjecucion: 'TipoEjecucion',
  listaCausalIncumplimento: 'CausalIncumplimiento'
};