export const environment = {
  production: true,
  urlRaiz: 'https://enovelsoluciones.sharepoint.com',
  urlWeb:'https://enovelsoluciones.sharepoint.com/sites/jam/solpes', 
  urlReltativa: '/sites/jam/solpes',
  listaEmpresas: 'Empresas',
  listaPaises: 'Paises',
  listaCategorias: 'Categorias',
  listaSubcategorias: 'Subcategorias',
  listaCondicionesContractuales: 'CondicionesContractuales',
  listaTiposSolicitud: 'TiposSolicitud',
  listaSolicitudes: 'Solicitudes',
  listaCondicionesTecnicasBienes: 'CondicionesTecnicasBienes',
  listaCondicionesTecnicasServicios: 'CondicionesTecnicasServicios',
  listaConfiguracion: 'ConfiguracionAplicacion',
  listaRecepcionBienes: 'RecepcionBienes',
  listaRecepcionServicios: 'RecepcionServicios',
  listaContratos: 'Contratos',
  listaResponsableProceso: 'ResponsableProceso',
  listaNotificaciones: 'Notificaciones',
  linkVistaEdicionContratos: '/Lists/Contratos/EdicionContratos.aspx'
};